sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"

before_install:
    docker build . --tag twentyfifth/ttrack-client:latest

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push twentyfifth/ttrack-client;
    fi