sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

before_install:
  - yarn run build
  - make GIT_COMMIT="$TRAVIS_COMMIT" VERSION=$TRAVIS_BUILD_NUMBER build
  - make start
  - docker-compose -f docker-compose.dev.yml ps

script:
  - make yarn test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make VERSION=$TRAVIS_BUILD_NUMBER ship;
    fi
