FROM node:5

MAINTAINER 25th-floor GmbH "team@25th-floor.com"
EXPOSE "8080"

# Prepare work directory
RUN mkdir /app
WORKDIR /app

# Installing incl. devDependencies
ADD ./package.json /app
RUN npm install

# Add all the additional source code
COPY . /app

ENV NODE_ENV production
RUN npm run build && \
	cp config/config.json.example config.json

CMD npm test
