version: '2'

services:
  ttrack-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ttrack-client
    environment:
      - API_URL=http://localhost:8000
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - 8080:80
