UPDATE periods SET per_comment = 'Neujahr' WHERE per_comment = 'Neujahr (Feiertag)';
UPDATE periods SET per_comment = 'Hl. Drei Könige' WHERE per_comment = 'Heiligen 3 koenige (Feiertag)';
UPDATE periods SET per_comment = 'Ostermontag' WHERE per_comment = 'Ostermontag (FEIERTAG)';
UPDATE periods SET per_comment = 'Staatsfeiertag' WHERE per_comment = 'Staatsfeiertag (Feiertag)';
UPDATE periods SET per_comment = 'Christi Himmelfahrt' WHERE per_comment = 'Christi Himmelfahrt (Feiertag)';
UPDATE periods SET per_comment = 'Pfingstmontag' WHERE per_comment = 'Pfingstmontag (Feiertag)';
UPDATE periods SET per_comment = 'Fronleichnam' WHERE per_comment = 'Fronleichnam (Feiertag)';
UPDATE periods SET per_comment = 'Mariä Himmelfahrt' WHERE per_comment = 'Mariä Himmelfahrt (Feiertag)';
UPDATE periods SET per_comment = 'Nationalfeiertag' WHERE per_comment = 'Nationalfeiertag (Feiertag)';
UPDATE periods SET per_comment = 'Allerheiligen' WHERE per_comment = 'Allerheiligen (Feiertag)';
UPDATE periods SET per_comment = 'Mariä Empfängnis' WHERE per_comment = 'Mariä Empfängnis (Feiertag)';
UPDATE periods SET per_comment = 'Heiliger Abend' WHERE per_comment = 'Heiliger Abend (Feiertag)';
UPDATE periods SET per_comment = 'Heiliger Abend' WHERE per_comment = 'Weihnachten';
UPDATE periods SET per_comment = 'Christtag' WHERE per_comment = 'Christtag (Feiertag)';
UPDATE periods SET per_comment = 'Stefanitag' WHERE per_comment = 'Stefanitag (Feiertag)';
UPDATE periods SET per_comment = 'Silvester' WHERE per_comment = 'Silvester (Feiertag)';
