export default [
    { house: 'House Allyrion of Godsgrace', motto: "No Foe May Pass" },
    { house: 'House Ambrose', motto: "Never Resting" },
    { house: 'House Arryn of the Eyrie', motto: "As High as Honor" },
    { house: 'House Ashford of Ashford', motto: "Our Sun Shines Bright" },
    { house: "House Baratheon of Storm's End", motto: "Ours is the Fury" },
    { house: 'House Beesbury of Honeyholt', motto: "Beware Our Sting" },
    { house: 'House Buckwell of the Antlers', motto: "Pride and Purpose" },
    { house: 'House Bulwer of Blackcrown', motto: "Death Before Disgrace" },
    { house: 'House Caron of Nightsong', motto: "No Song So Sweet" },
    { house: 'House Cerwyn of Cerwyn Castle', motto: "Honed and Ready" },
    { house: 'House Codd', motto: "Though All Men Do Despise Us" },
    { house: 'House Crakehall of Crakehall', motto: "None so Fierce" },
    { house: 'House Egen', motto: "By Day or Night" },
    { house: "House Flint of Widow's Watch", motto: "Ever Vigilant" },
    { house: 'House Follard', motto: "None so Wise" },
    { house: 'House Footly of Tumbleton', motto: "Tread Lightly Here" },
    { house: 'House Fossoway of Cider Hall', motto: "A Taste of Glory" },
    { house: 'House Fowler of Skyreach', motto: "Let Me Soar" },
    { house: 'House Graceford of Holyhall', motto: "Work Her Will" },
    { house: 'House Grandison of Grandview', motto: "Rouse Me Not" },
    { house: 'House Greyjoy of Pyke', motto: "We Do Not Sow" },
    { house: 'House Hastwyck', motto: "None So Dutiful" },
    { house: 'House Hightower of the Hightower', motto: "We Light the Way" },
    { house: 'House Hornwood of Hornwood', motto: "Righteous in Wrath" },
    { house: 'House Jordayne of the Tor', motto: "Let It Be Written" },
    { house: 'House Karstark of Karhold', motto: "The Sun of Winter" },
    { house: 'House Lannister of Casterly Rock', motto: "Hear Me Roar!" },
    { house: 'House Lonmouth', motto: "The Choice Is Yours" },
    { house: 'House Mallister of Seagard', motto: "Above the Rest" },
    { house: 'House Marbrand of Ashemark', motto: "Burning Bright" },
    { house: 'House Martell of Sunspear', motto: "Unbowed, Unbent, Unbroken" },
    { house: 'House Merryweather of Longtable', motto: "Behold Our Bounty" },
    { house: 'House Mooton of Maidenpool', motto: "Wisdom and Strength" },
    { house: 'House Mormont of Bear Island', motto: "Here We Stand" },
    { house: 'House Oakheart of Old Oak', motto: "Our Roots Go Deep" },
    { house: 'House Peckledon', motto: "Unflinching" },
    { house: 'House Penrose of Parchments', motto: "Set Down Our Deeds" },
    { house: 'House Piper of Pinkmaiden', motto: "Brave and Beautiful" },
    { house: 'House Plumm', motto: "Come Try Me" },
    { house: 'House Prester of Feastfires', motto: "Tireless" },
    { house: 'House Redfort of Redfort', motto: "As Strong as Stone" },
    { house: 'House Royce of Runestone', motto: "We Remember" },
    { house: 'House Sarsfield of Sarsfield', motto: "True to the Mark" },
    { house: 'House Serrett of Silverhill', motto: "I Have No Rival" },
    { house: 'House Smallwood of Acorn Hall', motto: "From These Beginnings" },
    { house: 'House Stark of Winterfell', motto: "Winter is Coming" },
    { house: 'House Stokeworth of Stokeworth', motto: "Proud to Be Faithful" },
    { house: 'House Swyft of Cornfield', motto: "Awake! Awake!" },
    { house: 'House Swygert', motto: "Truth Conquers" },
    { house: "House Tallhart of Torrhen's Square", motto: "Proud and Free" },
    { house: "House Targaryen of King's Landing", motto: "Fire and Blood" },
    { house: 'House Tarly of Horn Hill', motto: "First in Battle" },
    { house: 'House Tollett of the Grey Glen', motto: "When All is Darkest" },
    { house: 'House Toyne', motto: "Fly High, Fly Far" },
    { house: 'House Trant of Gallowsgrey', motto: "So End Our Foes" },
    { house: 'House Tully of Riverrun', motto: "Family, Duty, Honor" },
    { house: 'House Tyrell of Highgarden', motto: "Growing Strong" },
    { house: 'House Velaryon of Driftmark', motto: "The Old, the True, the Brave" },
    { house: 'House Waxley of Wickenden', motto: "Light in Darkness" },
    { house: 'House Wendwater', motto: "For All Seasons" },
    { house: 'House Wensington', motto: "Sound the Charge" },
    { house: 'House Westerling of the Crag', motto: "Honor, not Honors" },
    { house: 'House Wode', motto: "Touch Me Not" },
    { house: 'House Wydman', motto: "Right Conquers Might" },
    { house: 'House Yronwood of Yronwood', motto: "We Guard the Way" }
];
